/**
 * Signatures visuelles des plats : ce qui permet de les reconnaître sur une photo, et ce qui les
 * distingue de leurs sosies.
 *
 * Le modèle ne recevait que le nom de chaque plat et ses synonymes, rien sur son apparence :
 * trois pâtes blanchâtres lui étaient indiscernables, et du télibo était rendu « pâte de maïs ».
 *
 * GÉNÉRÉ depuis docs/guide_reconnaissance_plats.md, recherche confiée à un agent et relue.
 * Les confusions ne sont retenues que pour les féculents, les sauces et les plats complets :
 * ce sont les familles où les erreurs se produisent, et tout injecter doublerait le coût du scan.
 * Les lignes de certitude basse sont conservées — elles décrivent l'aspect sans prétendre
 * trancher — mais c'est là qu'il faudra revenir si une reconnaissance reste fausse.
 */

export type FoodAspect = { aspect: string; confusions: string[] };

export const FOOD_ASPECTS: Record<string, FoodAspect> = {
  telibo: { aspect: 'Pâte brun foncé à presque noire, lisse et élastique, servie en boule ou en portion façonnée à la main. La couleur sombre vient de la farine de cossettes d\'igname séchée.', confusions: ['pate_mais — la pâte de maïs est blanche ou crème ; le télibo est brun foncé à noir.', 'igname_pilee — l\'igname pilée fraîche est blanche et brillante ; le télibo est sombre et plus mat.', 'amiwo — l\'amiwo est rouge-orangé (huile, tomate) ; le télibo tire sur le brun-noir.', 'eba — l\'eba est crème à jaune et granuleuse ; le télibo est sombre et lisse.'] },
  bissap: { aspect: 'Liquide rouge profond à rubis, translucide, servi froid en verre, bouteille ou carafe. Pas de gaz visible.', confusions: [] },
  jus_gingembre: { aspect: 'Liquide jaune pâle à beige, souvent trouble, servi froid. Description non vérifiée sur photo.', confusions: [] },
  soda: { aspect: 'Bouteille ou canette de marque, liquide coloré (brun, orange, rouge) avec gaz ou mousse. Le contenant de marque est l\'indice principal.', confusions: [] },
  riz_blanc: { aspect: 'Grains longs, blancs, détachés ou légèrement collés, sans coloration. Servi en tas dans l\'assiette.', confusions: ['attieke — grains beaucoup plus petits, agglomérés, légèrement translucides.', 'riz_jollof — le riz jollof est coloré rouge-orangé sur tous les grains ; le riz blanc n\'a aucune teinte.', 'atassi — l\'atassi est mêlé de haricots visibles et teinté brun-jaune ou gris.', '**accompagnement** : sauces (tomate, arachide, feuilles) posées à côté ou dessus', '**noms régionaux** : riz nature', '**certitude** : basse', '**sources** : aucune source'] },
  riz_jollof: { aspect: 'Grains de riz uniformément rouge-orangé, cuits dans une sauce tomate à l\'huile, détachés les uns des autres. Les morceaux de viande et de légumes (carotte, poivron, haricots verts) sont souvent posés dessus.', confusions: ['thieboudienne — même riz rouge-orangé ; le thieboudienne porte du poisson (entier ou en gros tronçons) et de gros morceaux de légumes posés dessus.', 'atassi — riz plus brun, jaune ou gris, avec des haricots entiers visibles, sans teinte tomate.', 'amiwo — l\'amiwo est une masse compacte de pâte sans grains de riz distincts.', 'spaghetti — pâtes longues, pas des grains.', '**accompagnement** : poulet, bœuf ou poisson frit ; salade ; dodo (plantain frit)', '**noms régionaux** : riogla beninwa (Bénin), riz-o-gras (Burkina Faso), zaamè (Mali), benachin (Gambie), riz wolof, bènn tchin (Sénégal), ceebu jën', '**certitude** : moyenne', '**sources** : https://fr.wikipedia.org/wiki/Riz_wolof https://www.recettesafricaines.com/recettes/278 https://www.196flavors.com/fr/riz-wolof/ https://en.wikipedia.org/wiki/Jollof_rice'] },
  atassi: { aspect: 'Riz et petits haricots blancs à œil noir cuits ensemble ; les grains de riz sont teintés de brun, jaune ou gris, parfois rouge-brun (feuilles de sorgho). Les haricots entiers sont visibles dans les grains.', confusions: ['riz_jollof — le jollof est rouge-orangé uniforme, sans haricots visibles.', 'riz_blanc — le riz blanc n\'a ni haricots ni teinte.', 'haricots_niebe — les haricots seuls n\'ont pas de riz mêlé.', '**accompagnement** : sauce tomate (dja), œufs durs, wagashi, poisson ou poulet frit, piment', '**noms régionaux** : watché, waké (Nord Bénin), ayimolou, ayimonlou, watché (Togo), waakye (Ghana), irèsi ati ewa (Nigeria)', '**certitude** : moyenne', '**sources** : https://kelianfood.com/waakye-rice-ayimolou-atassi/ https://www.miammiambenin.fr/benin-delices/atassi-riz-aux-haricots/ https://visiter-le-benin.com/plat-typique-du-benin-l-atassi/ https://cuisinebeninoiseetdailleurs.com/atassi-watche-le-riz-aux-haricots-blancs-du-nord-benin/'] },
  attieke: { aspect: 'Semoule de manioc en très petits grains, blanc crème à ivoire, légèrement translucides, agglomérés et un peu collants. Servi en monticule.', confusions: ['gari — le gari est sec, grains plus gros, croquants, blancs ou jaunes (huile de palme) ; l\'attiéké est humide, fin, vapeur.', 'couscous_mil — le couscous de mil a des grains roulés plus ronds, teinte moins claire (non vérifié sur photo).', 'riz_blanc — grains de riz plus gros, longs et détachés.', '**accompagnement** : poisson braisé, alloco, sauce piment-oignon', '**noms régionaux** : attoukpou (Côte d\'Ivoire, grains accolés), garba (attiéké avec thon frit, Côte d\'Ivoire)', '**certitude** : moyenne', '**sources** : https://fr.wikipedia.org/wiki/Atti%C3%A9k%C3%A9 https://www.ajol.info/index.php/jab/article/view/159072 https://rayons-d-afrique.fr/foufou-plat-africain/'] },
  pate_mais: { aspect: 'Pâte blanche à crème, ferme, servie en boule ou en pâton, sans emballage. Cuite à l\'eau sans huile ni sel, donc sans coloration.', confusions: ['igname_pilee — l\'igname pilée est plus lisse et nettement plus élastique ; la pâte de maïs est plus mate et ferme.', 'eba — l\'eba est granuleuse en surface, parfois jaune ; la pâte de maïs est lisse.', 'akassa — l\'akassa est un gel lisse, vendu en pâtons enveloppés de feuilles, légèrement acide.', 'amiwo — l\'amiwo est rouge ou orangé (huile, tomate) ; la pâte de maïs est blanche.', 'foufou_manioc — très proche à la photo ; seul le contexte (sauce, région) aide.', '**accompagnement** : sauce tomate, sauce arachide, sauces gluantes (gombo, crincrin), sauce feuilles', '**noms régionaux** : wɔ̌ (fon, Bénin), pâte blanche (Bénin), akoumé (Togo), owo (Bénin), tô (Burkina Faso, Mali, Niger), ugali (Afrique de l\'Est)', '**certitude** : moyenne', '**sources** : https://fr.wikibooks.org/wiki/Livre_de_cuisine/W%C9%94%CC%8C_(p%C3%A2te_de_ma%C3%AFs) https://atlasculinaire.com/recettes/akassa--18c20828-c519-41ee-8c75-32ebb48a649b https://www.196flavors.com/togo-gboma-dessi-and-akoume/'] },
  amiwo: { aspect: 'Pâte de maïs rouge à orangée, cuite dans l\'huile avec tomate ou huile de palme ; masse compacte et grasse, servie en boule ou en tas. La teinte rouge est le signe distinctif.', confusions: ['pate_mais — la pâte blanche n\'a ni huile ni couleur.', 'riz_jollof — le jollof montre des grains de riz séparés ; l\'amiwo est une masse continue.', 'eba — l\'eba rouge (au palme) est granuleuse ; l\'amiwo est plus lisse et gras.', '**accompagnement** : viande (poulet, bœuf), parfois poisson fumé, crevettes séchées', '**noms régionaux** : djèwô, djèwɔ̌ (fon, Bénin), pâte rouge (Bénin)', '**certitude** : haute', '**sources** : https://fr.wikipedia.org/wiki/Amiw%C3%B4 https://benin360.com/cuisine-beninoise/ https://visiter-le-benin.com/12-plats-typiques-du-benin/'] },
  akassa: { aspect: 'Gel de maïs blanc à beige, ferme et lisse quand il est froid, souvent vendu en pâtons enveloppés de feuilles (teck, bananier). Peut aussi être servi sans emballage, en boule ou en bol.', confusions: ['pate_mais — le wɔ est cuit sans fermentation, plus ferme ; sans feuille d\'emballage.', 'bouillie_mais — la bouillie est la même base délayée, liquide ; l\'akassa est moulé, ferme.', 'foufou_manioc — texture élastique et collante ; l\'akassa est un gel net, légèrement acide.', '**accompagnement** : sauce tomate, sauce poisson ou viande, fromage de soja, bouille de maïs ; beignets de haricot (akara) en Nigeria', '**noms régionaux** : gui (fon), kannan (goun), èkò, eko (yoruba, Nigeria), agidi, aguidi (Nigeria), komu (haoussa), kafa (Ghana), akasan (Bénin), akpan (Togo ; au Bénin désigne plutôt la version bue), makumè (terme scientifique), lio (variante plus rigide, Abomey et Bohicon)', '**certitude** : haute', '**sources** : https://fr.wikipedia.org/wiki/Akassa_(p%C3%A2te) https://atlasculinaire.com/recettes/akpan-akassa--f9e8e5e5-0a89-4fed-bb5a-bed75aedd725 https://miniminamiam.com/akassa/ https://www.allnigerianrecipes.com/breakfast-recipes/agidi-eko/ https://en.wikipedia.org/wiki/Agidi'] },
  igname_pilee: { aspect: 'Pâte blanche à crème, très lisse, compacte et élastique, façonnée à la main en boule ou ovale. La surface est brillante et sans grain visible.', confusions: ['pate_mais — plus mate, plus ferme, moins élastique que l\'igname pilée.', 'foufou_manioc — presque indiscernable à la photo (pâte lisse et élastique) ; le contexte (région, sauce) est le seul indice.', 'eba — l\'eba a un grain visible en surface ; l\'igname pilée est parfaitement lisse.', 'akassa — gel plus net, souvent enveloppé de feuilles.', '**accompagnement** : sauce arachide, sauce tomate, sauces feuilles, viande, wagashi', '**noms régionaux** : agoun (centre Bénin), tchokourou (Nord Bénin), foutou (Côte d\'Ivoire), iyan (yoruba, Nigeria), pounded yam (Nigeria, Ghana)', '**certitude** : moyenne', '**sources** : https://eatafrika.com/2023/03/09/agoun-fufu-igname-pilee-au-mortier/ https://aupetitcreuxpace.fr/plats-africains/pounded-yam-cuisine-africaine/ https://eventeliteagency.com/evenementiel/nourriture-et-vin/ https://oukoikan.com/2023/03/14/agoun-accompagne-de-la-sauce-arachide/'] },
  foufou_manioc: { aspect: 'Pâte de manioc lisse et élastique, façonnée en boule ; le placali (manioc fermenté) est de texture gélatineuse et plus fondante. La couleur n\'est pas documentée avec certitude (blanc cassé à gris).', confusions: ['igname_pilee — presque indiscernable ; l\'igname pilée est blanche, très élastique ; le placali est plus fondant et plus acide.', 'eba — l\'eba est granuleuse en surface ; le foufou de manioc est lisse.', 'akassa — gel de maïs plus net, souvent emballé de feuilles.', 'pate_mais — plus mate, plus ferme que le foufou de manioc.', '**accompagnement** : sauce graine, sauce gombo, sauce arachide', '**noms régionaux** : placali (Côte d\'Ivoire), kokonte (Ghana, pâte de farine de cossettes de manioc), foutou (Côte d\'Ivoire)', '**certitude** : basse', '**sources** : https://www.nkosiagro.com/pages/guide-manioc-attieke-foufou-gari https://www.nkosiagro.com/en/blogs/culture-africaine/placali-pate-manioc-ivoirienne https://kelianfood.com/le-fufu-cest-quoi-origine-les-differents-types-de-fufu-en-afrique/ https://www.ajol.info/index.php/jab/article/view/159072'] },
  gari: { aspect: 'Granules secs de manioc torréfié, blanc crème, ou jaunes quand de l\'huile de palme est ajoutée. Grains irréguliers, petits, secs et non agglomérés.', confusions: ['attieke — l\'attiéké est humide, très fin, cuit à la vapeur, légèrement translucide ; le gari est sec et croquant.', 'eba — l\'eba est le gari déjà mélangé à l\'eau chaude, en pâte ; le gari sec reste en grains.', 'couscous_mil — grains roulés plus ronds et plus réguliers.', '**accompagnement** : souvent mangé avec de l\'eau, du sucre, de l\'arachide ou du poisson frit ; saupoudré sur des sauces', '**noms régionaux** : garri (Nigeria), gali (Bénin), couac (Guyane, préparation voisine)', '**certitude** : moyenne', '**sources** : https://fr.wikipedia.org/wiki/Gari_(farine) https://rtbfoods.cirad.fr/fr/les-produits/manioc/gari-eba/fiche-d-identite-produit https://lamaisondubenin.com/a-la-decouverte-du-eba-ou-piron/'] },
  eba: { aspect: 'Pâte épaisse de gari ébouillanté, crème à jaune (jaune avec gari à l\'huile de palme ou curcuma), légèrement granuleuse en surface, façonnée en boule. Elle se détache à la main.', confusions: ['pate_mais — pâte de maïs blanche et lisse ; l\'eba est granuleuse et crème à jaune.', 'igname_pilee — lisse et brillante ; l\'eba a un grain visible.', 'foufou_manioc — lisse et élastique ; l\'eba est plus rugueuse.', 'amiwo — l\'eba rouge au palme est granuleuse ; l\'amiwo est une pâte lisse, grasse et rouge.', '**accompagnement** : sauce egusi, sauce gombo, sauce tomate, sauce de sang de mouton ou de porc (kpètè)', '**noms régionaux** : piron, pinon, pilon, ba (Bénin), eba (Nigeria), piron jaune ou rouge (Bénin)', '**certitude** : moyenne', '**sources** : https://rtbfoods.cirad.fr/fr/les-produits/manioc/gari-eba/fiche-d-identite-produit https://www.recettes.ci/eba-pate-gari-farine-manioc-torrefiee-nigeria/ https://cuisinebeninoiseetdailleurs.com/piron-jaune-ou-eba-la-recette-express-a-base-de-gari/ https://cheflolaskitchen.com/how-to-make-eba/ https://lamaisondubenin.com/a-la-decouverte-du-eba-ou-piron/'] },
  haricots_niebe: { aspect: 'Petits haricots blancs à crème avec une tache noire (œil), cuits entiers, tendres. Servis en tas, parfois nappés de sauce tomate ou d\'huile.', confusions: ['atassi — l\'atassi mêle les haricots à du riz teinté.', 'beignets_haricot — les beignets sont frits et formés ; les haricots cuits restent entiers.', '**accompagnement** : sauce tomate (dja), huile de palme, alloco, piment', '**noms régionaux** : abodo (Bénin), ayikoun (Bénin), cornille, haricot à œil noir', '**certitude** : moyenne', '**sources** : https://www.okedjenou.com/recette/le-benga-national-atassi-recette-des-haricots-au-riz/ https://www.elviadelices.fr/products/friture-de-tomates-dja'] },
  alloco: { aspect: 'Rondelles ou tranches de plantain mûr frit, dorées à brun foncé avec des bords caramélisés, fondantes à l\'intérieur. Surface luisante d\'huile.', confusions: ['plantain_bouilli — le plantain bouilli est jaune pâle, sans croûte dorée ni brillance huileuse.', 'chips_plantain — chips fines, sèches, croustillantes, servies en sachet ; l\'alloco est épais et moelleux.', 'igname_frite — l\'igname frite est plus claire (chair blanche), moins sucrée et moins foncée.', '**accompagnement** : poisson braisé ou frit, poulet braisé, sauce piment-oignon, haricots', '**noms régionaux** : dodo (Bénin, Nigeria), amanda (Togo), missolè, misolé (Cameroun), makemba (RDC), kelewele (Ghana, version épicée), loco (Sénégal), claclo (Côte d\'Ivoire, beignet de plantain écrasé)', '**certitude** : haute', '**sources** : https://fr.wikipedia.org/wiki/Alloco https://fr.wikipedia.org/wiki/Banane_plantain_frite https://aistoucuisine.com/publications/banane-plantain-frite-alloco-dodo-makemba-missole https://www.aux-fourneaux.fr/alokos-alloco-bananes-plantain-frites-55173/'] },
  plantain_bouilli: { aspect: 'Tronçons de plantain avec ou sans peau, chair jaune pâle, cuite à l\'eau, sans croûte ni dorure. Description générale non vérifiée sur photo.', confusions: ['alloco — l\'alloco est doré, caramélisé, luisant ; le plantain bouilli est pâle et mat.', 'igname_bouillie — la chair de l\'igname est blanche à crème et plus dense ; celle du plantain est plus jaune.', 'manioc_bouilli — chair de manioc blanche et fibreuse au centre.', 'banane_douce — la banane douce est mangée crue et pelée, plus petite.', '**accompagnement** : sauce tomate, sauce piment, poisson', '**noms régionaux** : agbôkin (Bénin), plantain cuit', '**certitude** : basse', '**sources** : https://www.aux-fourneaux.fr/alokos-alloco-bananes-plantain-frites-55173/'] },
  igname_bouillie: { aspect: 'Tronçons ou rondelles d\'igname à chair blanche à crème (variété blanche) ou jaune, cuits à l\'eau, tenant leur forme. Peau retirée.', confusions: ['plantain_bouilli — le plantain est plus jaune ; l\'igname est plus blanche et farineuse.', 'manioc_bouilli — le manioc est plus fibreux, avec une fibre centrale.', 'igname_pilee — l\'igname pilée est une pâte lisse ; l\'igname bouillie reste en morceaux.', 'igname_frite — l\'igname frite est dorée, croustillante.', '**accompagnement** : sauce tomate pimentée, huile de palme, sauce piment', '**noms régionaux** : igname cuite', '**certitude** : moyenne', '**sources** : https://www.nkosiagro.com/pages/guide-igname-varietes-bienfaits-cuisson https://www.didiermathus.com/igname/'] },
  igname_frite: { aspect: 'Fines tranches ou bâtonnets d\'igname frits, dorés et croustillants à l\'extérieur. Chair claire à l\'intérieur.', confusions: ['alloco — l\'alloco est plus foncé, caramélisé et plus sucré ; l\'igname frite est plus claire.', 'igname_bouillie — l\'igname bouillie n\'est ni dorée ni croustillante.', 'chips_plantain — les chips de plantain sont beaucoup plus fines, en sachet.', '**accompagnement** : piment, sel, sauce légère', '**noms régionaux** : dundun (Nigeria), frites d\'igname', '**certitude** : moyenne', '**sources** : https://paulinhassika.over-blog.com/2026/07/igname-un-aliment-qui-porte-la-memoire-les-gestes-et-l-identite-du-benin.html'] },
  manioc_bouilli: { aspect: 'Tronçons de racine de manioc cuits à l\'eau, chair blanche et fibreuse. Les sources distinguent aussi le bâton de manioc (bobolo, chikwangue), pâte fermentée cuite à la vapeur enveloppée dans une feuille ; l\'aspect n\'en est pas vérifié sur photo.', confusions: ['igname_bouillie — chair plus farineuse et sans fibre centrale.', 'plantain_bouilli — chair plus jaune.', 'foufou_manioc — le foufou est une pâte lisse ; le manioc bouilli reste en tronçons.', '**accompagnement** : sauce tomate, sauce arachide, poisson fumé ; le bâton de manioc se mange avec le ndolé', '**noms régionaux** : chikwangue (RDC), bobolo (Cameroun), miondo (Cameroun), kwanga', '**certitude** : basse', '**sources** : https://fr.wikipedia.org/wiki/Atti%C3%A9k%C3%A9 https://www.recettesafricaine.com/ndole.html'] },
  pain: { aspect: 'Baguette dorée à croûte craquante, intérieur blanc et aéré. Servie entière, coupée ou en sandwich.', confusions: ['**accompagnement** : omelette, bouillie, beignets, haricots', '**noms régionaux** : pain, baguette', '**certitude** : basse', '**sources** : aucune source'] },
  spaghetti: { aspect: 'Pâtes longues et fines, jaune pâle (nature) ou rouge-orangé et brillantes quand elles sont sautées à la tomate ou à l\'huile. Servies en tas.', confusions: ['riz_jollof — grains de riz rouge-orangé, pas de pâtes longues.', 'riz_blanc — grains courts, pas de fils.', '**accompagnement** : œuf, sauce tomate, poulet frit', '**noms régionaux** : spaghetti sautés (Cameroun, Côte d\'Ivoire), macaroni', '**certitude** : basse', '**sources** : https://www.maggi.cm/en/'] },
  couscous_mil: { aspect: 'Petits grains roulés de farine de mil, cuits à la vapeur ; thiéré est fin, thiakry (grain moyen) est plus gros. La couleur est claire à grisâtre, non vérifiée sur photo.', confusions: ['attieke — grains d\'attiéké plus fins, collants, plus clairs et translucides.', 'gari — le gari est sec et irrégulier.', 'degue — le dèguè mêle ce couscous à du lait caillé blanc, servi froid en bol.', '**accompagnement** : sauce arachide (base), viande, poisson, légumes, lait caillé et sucre', '**noms régionaux** : saay, saac, futo, lacciri, basi (Sénégal, Gambie, Mauritanie), thiakry (grain moyen)', '**certitude** : basse', '**sources** : https://en.wikipedia.org/wiki/Thiere https://www.fruits-tropicaux.com/fr/cereales/107-thiakry-degue-de-mil-500g.html https://www.terramillet.com/cuisiner-les-millets/recettes-%C3%A0-partir-de-mil/'] },
  bouillie_mil: { aspect: 'Bouillie épaisse et lisse de farine de mil, souvent épicée (gingembre, clou de girofle) donc teintée. Servie chaude en bol, souvent avec lait concentré ou sucre.', confusions: ['bouillie_mais — quasi indiscernable à la photo ; la bouillie de mil est plus épicée et plus foncée, celle de maïs plus claire. Le contexte (hausa koko, épices) est l\'indice.', 'degue — le dèguè est froid, avec du lait caillé blanc et des grains de mil visibles.', 'akassa — l\'akassa est un gel ferme.', '**accompagnement** : beignets de haricot (akara, koose), beignets de farine, pain, lait, cacahuètes grillées', '**noms régionaux** : hausa koko (Ghana), coco baka (Côte d\'Ivoire), fondé (Sénégal), moni (Mali), koko goudaji (Niger)', '**certitude** : basse', '**sources** : https://www.myafroweek.com/la-bouillie-la-base-du-petit-dejeuner-africain/ https://kelianfood.com/5-idees-de-recette-a-base-de-mil/ https://blackinbourg.com/produit/blue-bay-hausa-koko-flour-1kg/ https://www.goldfoodafrica.com/produit/hausa-koko-600gr/'] },
  bouillie_mais: { aspect: 'Bouillie lisse, crème à blanche, devenant brillante en cuisant. Servie tiède en bol, parfois parfumée au gingembre.', confusions: ['bouillie_mil — quasi indiscernable ; celle de mil est plus épicée et plus foncée.', 'akassa — l\'akassa est le même maïs en gel ferme ; la bouillie est liquide.', 'degue — le dèguè contient des grains de mil et du lait caillé.', '**accompagnement** : beignets de haricot (akara), beignets de farine, pain, moin-moin (Nigeria)', '**noms régionaux** : akamu (Nigeria, igbo), ogi (Nigeria, yoruba), pap (Nigeria, Ghana), koko (Ghana)', '**certitude** : moyenne', '**sources** : https://kjsfood.com/recipe/akassa-koko-corn-porridge https://en.wikipedia.org/wiki/Ogi_(food) https://www.myafroweek.com/la-bouillie-la-base-du-petit-dejeuner-africain/'] },
  avocat: { aspect: 'Fruit à peau verte à brun-noir, chair vert pâle à jaune, gros noyau rond central. Présenté entier, en moitiés ou en tranches.', confusions: [] },
  banane_douce: { aspect: 'Petite banane jaune, pelée ou en tronçons, chair crème et molle. Mangée crue.', confusions: [] },
  mangue: { aspect: 'Fruit à peau verte, jaune ou rouge ; chair jaune-orangé, juteuse, noyau plat central. Présentée en tranches ou en cubes.', confusions: [] },
  ananas: { aspect: 'Chair jaune vif, fibreuse, servie en tranches ou en rondelles, souvent avec le cœur. Peau écailleuse brune et couronne de feuilles si entier.', confusions: [] },
  orange: { aspect: 'Fruit rond à peau orange, pelé ou en quartiers ou en demi-lune, chair orange segmentée et juteuse. Parfois coupée en spirale, vendue dans la rue.', confusions: [] },
  papaye: { aspect: 'Fruit allongé à peau jaune-vert, chair orange-rose tendre, cavité centrale remplie de petites graines noires rondes. Servie en tranches ou en cubes.', confusions: [] },
  crudites: { aspect: 'Salade verte, rondelles de tomate rouge, oignon blanc ou rouge émincé, parfois concombre, servis frais sans sauce visible. Éléments crus et nets, sans huile brillante.', confusions: [] },
  huile_palme: { aspect: 'Huile rouge à orange foncé, épaisse, semi-solide à température ambiante, opaque. Elle forme des taches ou une nappe rouge en surface des sauces.', confusions: [] },
  huile_vegetale: { aspect: 'Liquide jaune pâle à doré, limpide et translucide, en bouteille ou bidon. Brille sur les aliments frits.', confusions: [] },
  mayonnaise: { aspect: 'Crème épaisse, opaque, jaune très pâle à blanc cassé, déposée en cuillerée ou en filet. Mate à légèrement brillante.', confusions: [] },
  thieboudienne: { aspect: 'Riz rouge-orangé cuit dans une sauce tomate, avec poisson (entier ou en gros tronçons) et gros morceaux de légumes (carotte, chou, aubergine, manioc) posés dessus. Servi en grand plat commun.', confusions: ['riz_jollof — même riz rouge-orangé ; le jollof n\'a pas de poisson ni de gros légumes en surface.', 'poulet_dg — le poulet DG n\'a pas de riz et montre du plantain frit.', 'atassi — le riz atassi est brun et mêlé de haricots.', '**accompagnement** : citron, piment, tamarin', '**noms régionaux** : thieb, tieb, thiep (Sénégal), ceebu jën (wolof), thiebou guinar (version poulet), thiebou wekh (version blanche)', '**certitude** : moyenne', '**sources** : https://fr.wikipedia.org/wiki/Riz_wolof https://www.196flavors.com/fr/riz-wolof/ https://aistoucuisine.com/collections/ramadan/diner https://www.food.com/recipe/poulet-yassa-chicken-yassa-from-africa-14936'] },
  poulet_dg: { aspect: 'Poulet frit en morceaux mêlé à des rondelles de plantain frit, carottes, poivrons verts et rouges, haricots verts en morceaux, dans une sauce tomate légère. Plat coloré et sans riz.', confusions: ['poulet_frit — le poulet frit seul n\'a ni plantain ni légumes mêlés.', 'yassa_poulet — le yassa est enrobé d\'oignons caramélisés brun-jaune, sans plantain.', 'thieboudienne — plat de riz rouge avec poisson.', '**accompagnement** : souvent servi seul ou avec du riz ou du plantain', '**noms régionaux** : poulet directeur général, PDG (Cameroun)', '**certitude** : haute', '**sources** : https://www.ambacamvat.com/poulet-dg/ https://cuisinedumboa.com/poulet-dg/ https://www.196flavors.com/fr/cameroun-poulet-dg/ https://www.tabouencuisine.com/2016/04/poulet-dg-cameroun.html'] },
  yassa_poulet: { aspect: 'Morceaux de poulet nappés d\'une masse d\'oignons fondus brun-doré à jaune, dans une sauce citronnée liquide. Pas de riz dans la clé ; il est servi à côté, blanc.', confusions: ['poulet_braise — le poulet braisé est sec et noirci par la braise, sans masse d\'oignons.', 'poulet_dg — le DG montre du plantain et des légumes colorés, pas d\'oignons fondus.', 'viande_chevre — viande avec os, en sauce brune.', '**accompagnement** : riz blanc (servi à part)', '**noms régionaux** : yassa (Sénégal, Casamance), yassa au poisson ou au bœuf', '**certitude** : moyenne', '**sources** : https://fr.wikipedia.org/wiki/Yassa_(plat) https://www.food.com/recipe/poulet-yassa-chicken-yassa-from-africa-14936 https://lecontinentalrestaurant.fr/recettes-africaines/poulet-yassa-ou-yassa-au-boeuf/'] },
  degue: { aspect: 'Crème blanche épaisse de lait caillé ou yaourt sucré, avec de petits grains de mil visibles ; ressemble à un riz au lait. Servi froid en bol.', confusions: ['bouillie_mil — la bouillie est chaude, lisse, sans lait caillé blanc ni grains visibles.', 'couscous_mil — le couscous de mil sec n\'est pas mêlé à une crème.', 'bouillie_mais — bouillie lisse sans grains.', '**accompagnement** : sans indice (consommé en goûter, pas en fin de repas)', '**noms régionaux** : déguê (Côte d\'Ivoire, Mali, Guinée), thiakry (Sénégal), dégué (Bénin)', '**certitude** : haute', '**sources** : https://fr.wikipedia.org/wiki/D%C3%A8gu%C3%A9 https://www.couleurafrique.com/app/2020/04/14/made-in-benin-le-degue/ https://www.cahierderecettes.com/mil-au-lait-thiakry-degue/'] },
  poulet_braise: { aspect: 'Poulet entier ou en morceaux, peau brune à noircie par la braise, sec en surface. Déduit du mode de cuisson, non vérifié sur photo.', confusions: [] },
  poulet_frit: { aspect: 'Morceaux de poulet à croûte dorée à brune, uniforme, brillante d\'huile. Sans marques de braise.', confusions: [] },
  poisson_braise: { aspect: 'Poisson entier (tilapia, carpe, capitaine, bar) à peau marquée par la braise, souvent incisé et recouvert d\'une sauce tomate-piment ou d\'oignons. Servi entier sur plat.', confusions: [] },
  poisson_frit: { aspect: 'Poisson entier ou en tronçons à peau dorée à brune, croustillante, luisante d\'huile ; petits poissons entiers fréquents au bord des routes. Parfois arrosé de citron.', confusions: [] },
  poisson_fume: { aspect: 'Poisson sec, brun foncé à noir, raidi, souvent en morceaux ou entier recroquevillé ; la fumée donne cet aspect. Utilisé aussi émietté dans les sauces.', confusions: [] },
  crevettes_sechees: { aspect: 'Petites crevettes entières séchées et fumées, rigides, orange-brun, ou réduites en poudre fine. Vendues en tas ou en sachet.', confusions: [] },
  viande_boeuf: { aspect: 'Morceaux de bœuf cuits, bruns, en cubes ou en tranches, souvent dans une sauce ou une marinade. Non vérifié sur photo.', confusions: [] },
  viande_chevre: { aspect: 'Morceaux de chèvre ou de mouton cuits, avec os, bruns, irréguliers, souvent en sauce ou grillés. Non vérifié sur photo.', confusions: [] },
  suya: { aspect: 'Lamelles fines de viande sur pique en bois, enrobées de poudre brun-orangé (yaji : arachide, piment, paprika), grillées à la braise. Servies avec oignons crus et tomates.', confusions: [] },
  oeuf_dur: { aspect: 'Œuf ovale à blanc lisse, coupé en deux montrant le jaune, ou entier écalé. Parfois plongé dans une sauce tomate.', confusions: [] },
  omelette: { aspect: 'Œuf battu cuit à plat, jaune à doré, plié ou en galette, souvent avec oignons et tomates visibles. Souvent glissée dans un pain.', confusions: [] },
  wagashi: { aspect: 'Fromage ferme en bloc ou cubes, blanc ou rouge-orangé (coloré par feuille ou décoction de sorgho), ne fond pas. Texture compacte avec trous éventuels de moulage.', confusions: [] },
  wagashi_frit: { aspect: 'Cubes, tranches ou bâtonnets de fromage peul à croûte dorée à brune, croustillante à l\'extérieur, fondante à l\'intérieur. Luisant d\'huile.', confusions: [] },
  fromage_soja: { aspect: 'Fromage de soja coupé en losanges, jaune à doré (frit) ou blanc-ivoire (non frit), ferme, parfois coloré par une décoction de sorgho. Vendu en sachet ou à l\'unité dans la rue.', confusions: [] },
  beignets_haricot: { aspect: 'Boules ou galettes frites de pâte de haricots niébé battue, brun doré à l\'extérieur. Taille d\'une petite balle, vendus avec la bouillie.', confusions: [] },
  sauce_graine: { aspect: 'Sauce épaisse et nappante de pulpe de noix de palme, orange à rouge-orangé, avec une fine couche d\'huile rouge en surface. Morceaux de viande et de poisson fumé dedans, sans morceaux de tomate.', confusions: ['sauce_tomate — la sauce tomate est rouge foncé, concentrée et grasse ; la sauce graine est orange.', 'sauce_arachide — l\'arachide est cuivrée à brun-orangé, onctueuse ; la graine est plus orange vif. Distinction délicate à la photo.', 'huile_palme — l\'huile seule est un liquide gras rouge, sans corps de sauce.', '**accompagnement** : pâte de maïs, télibo, riz, igname pilée, foutou, attiéké', '**noms régionaux** : dékoun (Bénin), banga (Nigeria), abenkwan (Ghana), sauce palmiste', '**certitude** : haute', '**sources** : https://lamaisondubenin.com/la-sauce-dekoun-ou-sauce-graine/ https://www.fournil-des-rois.fr/sauce-graine/ https://ramentafaim.fr/sauce-graine/ https://kjsfood.com/recipe/seed-sauce-palm-nuts'] },
  sauce_arachide: { aspect: 'Sauce épaisse et onctueuse brun-cuivré à brun-orangé, avec une couche d\'huile ambrée en surface. Contient viande, poulet ou poisson ; la version béninoise peut être plus rouge (tomate, huile rouge).', confusions: ['sauce_graine — la graine est plus orange vif ; l\'arachide est plus brune et crémeuse.', 'sauce_tomate — la tomate est rouge foncé, sans onctuosité crémeuse.', 'ndole — le ndolé contient des feuilles vertes amères visibles dans une base d\'arachide.', 'sauce_pistache — la pistache est plus grumeleuse, souvent avec feuilles vertes.', '**accompagnement** : igname pilée, pâte blanche, riz, poulet fumé, wagashi', '**noms régionaux** : mafé, maafe, tigadèguènan (Mali), groundnut soup (Ghana, Nigeria), azindessi (Bénin)', '**certitude** : moyenne', '**sources** : https://www.nkosiagro.com/pages/guide-pate-arachide-mafe https://atlasculinaire.com/recettes/sauce-darachide-guineenne-mafe-conakry--ebd23dba-d99c-4485-8729-38438e298c4f https://beninchezmoi.com/blogs/infos/recette-de-la-sauce-arachide-beninoise-cremeuse-et-reconfortante https://oukoikan.com/2023/03/14/agoun-accompagne-de-la-sauce-arachide/'] },
  sauce_tomate: { aspect: 'Pâte de tomate longuement frite à l\'huile, rouge foncé, épaisse, grasse, avec l\'huile qui remonte en surface. Servie en petite portion à côté ou nappée, parfois avec œufs durs entiers.', confusions: ['sauce_graine — la graine est orange et plus fluide ; la sauce tomate est rouge foncé et dense.', 'sauce_arachide — l\'arachide est cuivrée et crémeuse.', 'sauce_claire — la sauce claire est un bouillon léger rouge-orangé avec poisson ; la sauce tomate est une pâte épaisse.', 'huile_palme — l\'huile de palme est un liquide gras sans morceaux ni pâte.', 'sauce_pistache — la pistache est plus grumeleuse, avec feuilles ou graines moulues.', '**accompagnement** : atassi, riz, haricots, igname, pâtes, poisson frit', '**noms régionaux** : dja, friture de tomate, jus (Bénin, Togo), tomato stew (Nigeria, Ghana), m\'gbagba, nougbagba, amivôvô dja (version à l\'huile de palme, Bénin)', '**certitude** : haute', '**sources** : https://www.papillesetpupilles.fr/2019/10/dja-la-sauce-tomate-du-benin.html/ https://lesgourmandisesdekarelle.com/recettes-lgdk/recettes-africaines/faire-dja-petite-sauce-tomate-beninoise/ https://lanouvelletribune.info/2020/10/la-sauce-tomate-et-quelques-varietes-dans-la-gastronomie-africaine/ http://wezonblog.blogspot.com/2013/10/attassi-la-friture-de-tomate.html'] },
  sauce_feuilles: { aspect: 'Sauce vert foncé à brun-vert, épinards ou gboma cuits puis hachés grossièrement, mêlés à de l\'huile (rouge ou végétale), avec morceaux de viande, poisson fumé ou crevettes. Texture onctueuse, non filante.', confusions: ['sauce_crincrin — le crincrin est filant, vert profond lustré avec yeux d\'huile rouge, feuilles minuscules battues ; les feuilles hachées de la sauce feuilles ne filent pas.', 'sauce_feuille_manioc — feuilles de manioc finement pilées, plus uniformes ; la sauce feuilles montre des morceaux d\'épinard plus visibles.', 'ndole — ndolé vert foncé dans une base d\'arachide crémeuse.', 'sauce_pistache — la pistache est épaisse, grumeleuse avec les graines moulues, parfois avec épinards.', '**accompagnement** : pâte de maïs, akassa, ablo, riz, télibo', '**noms régionaux** : gboma dessi (Togo), mantindjan (Bénin), shoko (Ghana), efo riro (Nigeria), gboman, fonman, tchiayo, amanvivè (Bénin, leafy sauces)', '**certitude** : moyenne', '**sources** : https://www.196flavors.com/togo-gboma-dessi-and-akoume/ https://saveurstogo.com/gboma-dessi-sauce-togolaise/ https://www.lesdelicesdejessy.com/sauce-epinards-gboma-mantindjan https://www.elviadelices.fr/products/telibo'] },
  sauce_gombo: { aspect: 'Sauce gluante et filante à base de gombos coupés en rondelles ou en cubes, avec poisson fumé, crevettes, crabe ou viande. Couleur non documentée avec certitude (varie selon l\'huile rouge ajoutée).', confusions: ['sauce_crincrin — le crincrin est vert profond et battu, sans rondelles de gombo ; le gombo montre des morceaux et des graines.', 'sauce_feuilles — la sauce feuilles n\'est pas filante.', '**accompagnement** : pâte de maïs, pâte de manioc, riz, eba, placali, télibo', '**noms régionaux** : févi, fevi, abémon (Bénin), fetri dessi (Togo), kopé (Côte d\'Ivoire), okro stew (Ghana), gan-nah (Mali), soupoukandja (Sénégal), okra', '**certitude** : moyenne', '**sources** : https://fr.wikipedia.org/wiki/Sauce_gombo https://eatafrika.com/2024/09/11/recette-de-la-sauce-gombo-beninoise-inratable-et-delicieuse/ https://lanouvelletribune.info/2020/07/7-sauces-aux-feuilles-legumes-africaines-a-connaitre-absolument/'] },
  sauce_crincrin: { aspect: 'Sauce vert foncé et lustrée, très filante (fil étirable entre la cuillère et le bol), avec yeux d\'huile rouge en surface. Contient poisson fumé, crabe, crevettes ; feuilles de corète battues, non visibles en morceaux.', confusions: ['sauce_gombo — le gombo montre des morceaux de gombo et des graines.', 'sauce_feuilles — la sauce feuilles est non filante, avec feuilles hachées visibles.', 'sauce_feuille_manioc — sauce de feuilles de manioc non filante, plus pâteuse.', '**accompagnement** : pâte de maïs (akoumé), télibo, ajoutée dans les sauces tomate ou arachide', '**noms régionaux** : ninnouwi, crincrin, craincrain (Bénin), adémè (Togo), ewedu (Nigeria), kplala (Côte d\'Ivoire), fakouhoy (Mali), mouloukhia', '**certitude** : moyenne', '**sources** : https://atlasculinaire.com/recettes/akoume-sauce-ademe--54f4045f-0aa2-4c63-86c9-520989ecba20 https://beninwebtv.bj/cuisine-recette-facile-de-sauce-crincrin-a-la-togolaise-ademe/ https://lamaisondubenin.com/la-sauce-crincrin-ou-ninnouwi/'] },
  sauce_pistache: { aspect: 'Ragoût épais, grumeleux, à base de graines de melon moulues, avec huile de palme rouge, souvent des feuilles vertes (épinards) et des morceaux de viande et de poisson. Les graines absorbent l\'humidité et forment des amas.', confusions: ['sauce_arachide — l\'arachide est lisse, crémeuse et cuivrée ; la pistache est grumeleuse.', 'sauce_feuilles — la sauce feuilles est vert foncé, non grumeleuse, sans graines moulues.', 'sauce_graine — la graine est lisse, orange ; la pistache est grumeleuse, plus jaune-verte.', '**accompagnement** : igname pilée, eba, riz, akassa', '**noms régionaux** : egusi, egousi (Nigeria), egoussi dessi (Togo), agoussi (Bénin), pistache africaine, met de pistache (Cameroun)', '**certitude** : moyenne', '**sources** : https://www.196flavors.com/fr/nigeria-soupe-degousi-sauce-pistache/ https://saveurstogo.com/egoussi-dessi-sauce-togolaise/ https://www.peko-peko.fr/recettes/egusi-soup/ https://en.wikipedia.org/wiki/Egusi_sauce'] },
  sauce_claire: { aspect: 'Bouillon léger et fluide, légèrement coloré (rouge-orangé tomate), avec tronçons de poisson frais et peu de matière épaisse. Se mange comme une soupe.', confusions: ['sauce_tomate — la sauce tomate est une pâte épaisse ; la sauce claire est un liquide à tronçons de poisson.', 'sauce_arachide — onctueuse et opaque.', '**accompagnement** : attiéké, foufou, igname, riz', '**noms régionaux** : pepper soup (Nigeria), light soup (Ghana), omi ôbè (yoruba), n\'sounou ssin (fon), bouillon de machoiron', '**certitude** : moyenne', '**sources** : https://www.cuisinedecheznous.net/blog/2022/10/29/une-delicieuce-sauce-claire-au-poisson-frais-pour-le-plaisir/ https://lanouvelletribune.info/2020/10/la-sauce-tomate-et-quelques-varietes-dans-la-gastronomie-africaine/ https://glance-magazine.com/2024/08/18/bouillon-de-machoiron-ou-pepper-soup/'] },
  ndole: { aspect: 'Feuilles amères vert foncé, bouillies et hachées, mêlées à une pâte d\'arachide crémeuse, avec crevettes, poisson fumé ou viande. Plat vert foncé à brun-vert.', confusions: ['sauce_feuilles — la sauce feuilles est sans base d\'arachide crémeuse.', 'sauce_feuille_manioc — feuilles de manioc finement pilées dans huile de palme, sans crème d\'arachide.', 'sauce_arachide — l\'arachide est cuivrée, sans feuilles vertes.', '**accompagnement** : bâton de manioc (miondo, bobolo), plantain frit, riz', '**noms régionaux** : ndolè (Cameroun)', '**certitude** : moyenne', '**sources** : https://recettesdafrique.com/recette/le-ndole/ https://www.recettesafricaine.com/ndole.html https://gastronomieivoirienne.wordpress.com/2017/04/13/recettes-du-cameroun-le-ndole/'] },
  sauce_feuille_manioc: { aspect: 'Feuilles de manioc finement pilées, mijotées longuement dans l\'huile de palme, avec poisson fumé ou viande. Sauce vert foncé, dense, d\'aspect uniforme.', confusions: ['sauce_feuilles — épinards plus grossièrement hachés, plus de morceaux visibles.', 'ndole — ndolé crémeux à l\'arachide.', 'sauce_crincrin — le crincrin est filant, non pâteux.', '**accompagnement** : manioc, riz, pain, plantain frit, igname', '**noms régionaux** : saka-saka (Congo-Brazzaville, Angola), pondu, mpondu (RDC), madaba, sauce feuilles de manioc', '**certitude** : moyenne', '**sources** : https://www.nkosiagro.com/blogs/culture-africaine/pondu-saka-saka https://mddolce.com/fran/pondu-saga-saga https://enviesdafrique.fr/produit/saka-saka-ou-pondu-congele-du-cameroun-500-grammes/'] },
  arachides_grillees: { aspect: 'Cacahuètes décortiquées ou en coque, brun clair à doré, grillées, sèches, servies en tas ou en sachet. Non vérifié sur photo.', confusions: [] },
  beignet_farine: { aspect: 'Boule ronde de pâte de farine levée frite, caramel à brun doré, brillante et gonflée. Parfois roulée dans du sucre.', confusions: [] },
  chips_plantain: { aspect: 'Tranches très fines de plantain frites, sèches et croustillantes, jaune doré, en sachet ou en tas. Plates et translucides.', confusions: [] },
  lait_concentre: { aspect: 'Liquide épais, crème à beige, visqueux, versé en filet ou vu en boîte de conserve ou en tube de marque. Non vérifié sur photo.', confusions: [] },
  sucre: { aspect: 'Grains blancs fins en poudre ou morceaux (cubes), cristallins, secs. En tas, en sachet ou en cuillère.', confusions: [] },
};
